FROM postgis/postgis:16-3.4

ENV POSTGRES_DB=appdb
ENV POSTGRES_USER=appuser
ENV POSTGRES_PASSWORD=apppassword

# Expose PostgreSQL port
EXPOSE 5432

# docker build -t my-postgis-db .
# docker run -p 5432:5432 my-postgis-db